### ISSUE TITLE
airportsStorage.airports is empty

### ISSUE THREAD

**Issue by Holimolido** [KosyanMedia/Aviasales-iOS-SDK#111]
Hi, `AviasalesSDK.sharedInstance().airportsStorage.airports()` is empty in 4.0.1, but it works in 3.1.3 and new app [Travelpayouts Travel App iOS](https://github.com/travelpayouts/travel-app-ios). I'm sure the apiToken, partnerMarker and locale are correct, because of true value in AviasalesSDK.wasConfigured and working the same code in other versions.

**Comment by glassoff** [comment]
Hello! We don't support this version of SDK. We recommend to migrate on https://github.com/travelpayouts/travel-app-ios , which contains more features.
