### ISSUE TITLE
Integrate with Libraries 

### ISSUE THREAD

**Issue by LegoTechApps** [KosyanMedia/Aviasales-iOS-SDK#18]
Hello Avia team,

**I followed this guid:**
https://github.com/KosyanMedia/Aviasales-iOS-SDK/wiki/Connecting-the-template-project

**& every time, files are missing:** 
1. AviasalesSDKTemplateBundle
2. libAviasalesSDKTemplateLibrary.a

i tried lot of times for days
Am i missing something? (step/installation?)

**Comment by sevabill** [comment]
If you use submodules, please be sure to run
```
cd Aviasales-iOS-SDK/   
git checkout v1.3.2    
```
in Step 1.
If you aren't using submodules, please get the code from here: 
> https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/v1.3.2
(code in master branch is currently in development)

**Comment by LegoTechApps** [comment]
thank you
its working perfect


Ofir Malachi, IOS Developer. Israel.
_________________
Mail iPhoneTelAvivi@Gmail.com <mailto:iPhoneTelAvivi@Gmail.com>
website http://www.legotechapps.com/ <http://www.legotechapps.com/>
LinkedIN https://www.linkedin.com/profile/view?id=219184724 <https://www.linkedin.com/profile/view?id=219184724>

**Comment by vokrut** [comment]
I'm try too using this instructions and stuck on this step. Can you help me?
I have all files, but it's no possible to add file libAviasalesSDKTemplateLibrary.a to Target Dependencies. There are only AviasalesSDKTemplate, AviasalesSDKTemplateTests, AviasalesSDKTemplateLibrary, AviasalesSDKTemplateBundle
![screen shot 2016-07-15 at 13 22 17](https://cloud.githubusercontent.com/assets/14891272/16872926/5e961344-4a90-11e6-98df-8ab4354256f2.png)

**Comment by mwurm93** [comment]
Where is the tutorial for integrating the template project into an existing project?
