### ISSUE TITLE
Integrated your sdk with cocoapods and it is not working

### ISSUE THREAD

**Issue by joaopdcgarcia** [KosyanMedia/Aviasales-iOS-SDK#22]
Some API endpoints are unresponsive and some don't work properly. e.g. : 

```
[[AviasalesSDK sharedInstance] searchAirportsWithString:@"LISBOA" completion:^(NSArray *airports, NSError *error){

        if(!error)
        NSLog(@"airports %@", airports);
        else{
            NSLog(@"error %@",error);
        }
    }];
```

Returns: 

> Error Domain=AviasalesSDK Code=404 "Didn't find any airport with requested search string" UserInfo={NSLocalizedDescription=Didn't find any airport with requested search string}

```
[[AviasalesSDK sharedInstance] requestAirportByName:@"LISBOA" completion:^(AviasalesAirport *airport, NSError *error){

        if(!error)
        NSLog(@"airport %@", airport);
        else{
            NSLog(@"error %@",error);
        }
    }];
```

Doesn't return.

Is the API still working or not? @sevabill @diniska

**Comment by sevabill** [comment]
Please use 
`- (void)searchAirportsWithString:localCompletion:webCompletion:`
as "lisboa" cannot be found in local database. WebCompletion will return airport you are looking for.
By the way, SDK version available through cocoapods is still in development, so if you'd like to have a stable version, consider using classing integration flow (https://github.com/KosyanMedia/Aviasales-iOS-SDK/wiki/Connecting-the-template-project) for stable release (https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/v1.3.2).
Thanks for pointing out the problem with `requestAirportByName:`.
Sorry for inconvenience.

**Comment by joaopdcgarcia** [comment]
I've created a new project from scratch and integrated your static lib libAviasales.a. 
All methods that I've tried don't work. 
Using 
> - (void)searchAirportsWithString:localCompletion:webCompletion:
```

[[AviasalesSDK sharedInstance] searchAirportsWithString:@"BCN" localCompletion:^(NSArray *airports, NSError *error){
        
        if(!error)
            NSLog(@"local airports %@", airports);
        else{
            NSLog(@"local error %@",error);
        }
        
    } webCompletion:^(NSArray *airports, NSError *error){
        
        if(!error)
            NSLog(@"web airports %@", airports);
        else{
            NSLog(@"web error %@",error);
        }
    }];
```

Returns : 
`local error Error Domain=AviasalesSDK Code=404 "Didn't find any airport with requested search string" UserInfo={NSLocalizedDescription=Didn't find any airport with requested search string}
2016-05-28 00:48:19.345 TripRoulette[332:75125] web airports (
)`

Also, 

> - (void) requestAirportByIATA: (NSString *) IATA completion: (void (^) (AviasalesAirport * airport, NSError * error)) completion; 

 with "BCN" as IATA, also doesn't return... 

I'm sorry to say that I was excited about your framework after reading online about it in multiple articles/links like this one http://blog.travelpayouts.com/en/free-flight-search-mobile-sdk/ and getting disappointed on its performance. It is currently broken.

**Comment by sevabill** [comment]
Please checkout [new SDK](https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases) and [new integration steps](https://github.com/KosyanMedia/Aviasales-iOS-SDK/blob/master/README_EN.md)
