### ISSUE TITLE
Integrate with template

### ISSUE THREAD

**Issue by vokrut** [KosyanMedia/Aviasales-iOS-SDK#24]
I cann't do this step "Add libAviasalesSDKTemplateLibrary.a to "Target Dependencies""
A have all files but i haven't possibility to do this because there no this file. Can you help me with this problem?
![screen shot 2016-07-15 at 13 22 17](https://cloud.githubusercontent.com/assets/14891272/16873192/e7d94c2e-4a91-11e6-890d-fb3a568dd752.png)

**Comment by sevabill** [comment]
Please checkout [new SDK](https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases) and [new integration steps](https://github.com/KosyanMedia/Aviasales-iOS-SDK/blob/master/README_EN.md)
