### ISSUE TITLE
Не работают кнопки выбора городов

### ISSUE THREAD

**Issue by OXYGENIUMMM** [KosyanMedia/Aviasales-iOS-SDK#25]
Привет, ребята. Скачал текущую версию. При попытке запустить в симуляторе из Xcode 7.3.1 ругался на отсутствие Podfile.lock, Manifest и пр. Лечится удалением "AviasalesSDKTemplate.xcworkspace" + pod install.

сейчас имеются две проблемы: 

1. на главном экране не работают кнопки выбора городов;
2. На симуляторе выставлен русский язык, а в приложении всё на английском.

**Comment by mkll** [comment]
Язык в SDK зависит не от языка симулятора, а от его региона. Выставьте регион Россия - будет по-русски.

**Comment by reydan** [comment]
@OXYGENIUMMM достаточно было просто `pod install`.
скачал сейчас последний релиз, собрал, запустил в эмуляторе — выбор города работает: https://cl.ly/gtKd

**Comment by OXYGENIUMMM** [comment]
@reydan Вы о версии v1.3.2? Я имел в виду текущую версию с master ветки

**Comment by reydan** [comment]
@OXYGENIUMMM мы совсем скоро выпустим большое обновление SDK, а пока что лучше брать [релиз 1.3.2](https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/v1.3.2)

**Comment by OXYGENIUMMM** [comment]
@reydan релиз 1.3.2 вроде собирается с product > archive, но органайзер не всплывает, и после открытия вручную, я не вижу приложения AviasalesSDKTemplate.
Не подскажете, в чём дело?

**Comment by diniska** [comment]
@OXYGENIUMMM Надо поставить Skip Install для Release -> NO.
Ну и bitcode отключить.

![2016-08-10 15 46 42](https://cloud.githubusercontent.com/assets/2674368/17554079/3e5e3590-5f1a-11e6-90e9-f33268fd7b99.png)

**Comment by OXYGENIUMMM** [comment]
@reydan благодарю!
Сейчас при поиске всплывает алерт "Sorry, service temporarily unavailable"
В charles proxy получаю следующую картину:
![2016-08-10 17 07 45](https://cloud.githubusercontent.com/assets/14890007/17556973/1b7bcdb8-5f1e-11e6-95de-f7f1e03e17d7.png)
![2016-08-10 17 07 49](https://cloud.githubusercontent.com/assets/14890007/17556974/1ba56164-5f1e-11e6-858a-d714a3f305d5.png)

**Comment by reydan** [comment]
@OXYGENIUMMM обратите внимание на этот [документ](https://github.com/KosyanMedia/Aviasales-iOS-SDK/wiki/Использование-шаблонного-проекта-в-приложении)

**Comment by OXYGENIUMMM** [comment]
Проблема была в криво скопированном токене.
Благодарю за помощь!

**Comment by reydan** [comment]
Пожалуйста ;)
