### ISSUE TITLE
ERROR ITMS-90171

### ISSUE THREAD

**Issue by AlexanderTim** [KosyanMedia/Aviasales-iOS-SDK#30]
Здравствуйте!
При отправке приложения в AppStore возникает ошибка ERROR ITMS-90171
Скрин прилагаю:
![1](https://cloud.githubusercontent.com/assets/8998256/18880738/fc288cca-84e9-11e6-8a30-6f242d82200c.jpg)

**Comment by OXYGENIUMMM** [comment]
У меня такая же ошибка: ![2016-09-26 22 01 59](https://cloud.githubusercontent.com/assets/14890007/18881304/78f8a822-84e3-11e6-8fb2-cab044882907.png)

**Comment by diniska** [comment]
Исправлено в https://github.com/KosyanMedia/Aviasales-iOS-SDK/commit/e8b749061147b7c22336055c600eb68b04b059f6. Скоро выйдет версия 2.0.1.

**Comment by AlexanderTim** [comment]
Заменил строчку
 PODS:
AviasalesSDK 
на AviasalesSDK (2.0.1-beta2)
и
SPEC CHECKSUMS:
AviasalesSDK: 38fabf85cc48a2a07076898ea62510eca20c2989
на  AviasalesSDK: 745d61f1483bd2e95b5032d190db07728083aa77
Переинсталировал CocoaPod, однако, таже ошибка осталась при отправке в AppStore

**Comment by mkll** [comment]
Отсюда: http://stackoverflow.com/questions/16424431/invalid-bundle-structure-ios

Some developers have hit this issue when integrating the Apptentive iOS SDK. Making the same error with other 3rd-party SDKS will cause the same issue.

Invalid Build Structure - The binary file 'YourApp.app/libApptentiveConnect.a' is not permitted. Your app may contain only one executable file."

This error occurs when the Apptentive static library is copied to the app bundle.
libApptentiveConnect.a **should be added** to the target's Link Binary with Libraries build phase.
It **should not be added** to the target's Copy Bundle Resources build phase.

**Comment by mkll** [comment]
Вот еще: http://onebigfunction.com/ios/2015/03/15/invalid-bundle-structure/

**Comment by AlexanderTim** [comment]
Во вкладке Copy Bundle Resourses вроде как порядок.
Вот смущают 3 файла слева, выделенные красным, похоже они должны быть, но не скачались
![5](https://cloud.githubusercontent.com/assets/8998256/18913954/f9d4c152-859b-11e6-9f76-78ff6ae7a0d5.png)

**Comment by AlexanderTim** [comment]
В папке Products тоже два файла красным

**Comment by mkll** [comment]
@AlexanderTim Особенно первый "красный" - собственно сам фреймворк AviasalesSDK.

**Comment by AlexanderTim** [comment]
Да, но почему название есть, а самого фрейворка вроде как нет?

**Comment by diniska** [comment]
Вышла версия 2.0.1 с исправлением выкладки в App Store: https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/2.0.1

**Comment by AlexanderTim** [comment]
Спасибо, отправка работает.
