### ISSUE TITLE
При поиске в эмуляторе не может подключиться к Jetradar

### ISSUE THREAD

**Issue by AlexanderTim** [KosyanMedia/Aviasales-iOS-SDK#31]
Здравствуйте!
При поиске в эмуляторе Xcode возникает ошибка, скрин прилагаю:
![3](https://cloud.githubusercontent.com/assets/8998256/18880957/b85f7c3c-84ea-11e6-85c5-7819d1dcf707.png)

**Comment by OXYGENIUMMM** [comment]
@AlexanderTim у Вас APIToken и PartnerMarker указаны?

**Comment by AlexanderTim** [comment]
Конечно, рекламный ключ для appodeal тоже.

**Comment by sevabill** [comment]
@AlexanderTim воспроизводится стабильно? Это наблюдается только на симуляторе или на реальном устройстве тоже? Firewall или proxy не может быть причиной? Проверьте, пожалуйста, в командной строке: `ping -c 4 yasen.aviasales.ru`

**Comment by AlexanderTim** [comment]
Стабильно ошибка идет на эмуляторе. Реального устройства от Apple у меня, к сожалению, нет.
Пинг идет нормально:
![ping](https://cloud.githubusercontent.com/assets/8998256/18911773/057419f6-8590-11e6-830a-2544ba16b695.jpg)

**Comment by sevabill** [comment]
@AlexanderTim проверьте, что на странице https://www.travelpayouts.com/developers/api в вашем личном кабинете открыт доступ к "Mobile SDK for iOS and Android":

![screen shot 2016-09-28 at 14 55 51](https://cloud.githubusercontent.com/assets/449585/18912565/b3e00374-858b-11e6-8d6c-2f8989e49856.png)

**Comment by AlexanderTim** [comment]
Доступ открыт

**Comment by AlexanderTim** [comment]
В новой версии сообщение без скобок, собачки и знака %
![error](https://cloud.githubusercontent.com/assets/8998256/18955358/207c580c-8668-11e6-9921-6f520f148fb8.png)

**Comment by AlexanderTim** [comment]
Конечно, появилось подозрение, что неправильно ключи прописаны, но вроде как все верно, пробел пробовал убирать, не помогло:
![kluchi](https://cloud.githubusercontent.com/assets/8998256/18957058/b663b7b0-866e-11e6-9514-751741da432a.jpg)

**Comment by sevabill** [comment]
@AlexanderTim да, перепутаны местами маркер и токен

**Comment by AlexanderTim** [comment]
Именно так. Невнимательность... Благодарю за помощь
