### ISSUE TITLE
Ошибка сборки после выгрузки в itunesconnect

### ISSUE THREAD

**Issue by OXYGENIUMMM** [KosyanMedia/Aviasales-iOS-SDK#32]
После обновления до 2.0.1 билд отправляется в айтюнс, но там выдаёт ошибку:
![2016-09-29 21 23 44](https://cloud.githubusercontent.com/assets/14890007/18966818/6379ed86-868b-11e6-86c8-74a395827f2e.png)

**Comment by sevabill** [comment]
@OXYGENIUMMM какую-то подробную информацию на почту не прислали?

**Comment by OXYGENIUMMM** [comment]
Нет. В проекте в списке предупреждений есть такие:
![2016-09-30 12 56 43](https://cloud.githubusercontent.com/assets/14890007/18988057/8d467c74-870d-11e6-869d-362e94af269f.png)

**Comment by sevabill** [comment]
Эти предупреждения мы тоже наблюдаем, но при этом билды заливаются и процессятся нормально.
Удостоверьтесь, что письма от Apple точно не было — обычно в таких случаях приходит письмо с объяснением ошибки (может попало в спам). 
Есть одно предположение: не добавлены иконки (нужно добавить иконки для всех поддерживаемых устройств в App.xcassets -> AppIcon)

**Comment by OXYGENIUMMM** [comment]
Да, заказчик отписал, что есть письма на его адрес. Текст такой:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
