### ISSUE TITLE
Ошибка билда в itunesconnect

### ISSUE THREAD

**Issue by OXYGENIUMMM** [KosyanMedia/Aviasales-iOS-SDK#34]
Версия 2.0.1
Отправленный в itunesconnect билд помечен ошибкой и на почту приходит уведомление следующего содержания:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

Функционально код я не менял, только были изменены цвета и иконки.

**Comment by mkll** [comment]
@OXYGENIUMMM Вам приготовили блюдо, которое надо прожевать, а потом проглотить. А вы пытаетесь сразу проглотить и жалуетесь, что не глотается. То, что вам написала Apple, относится к [App Store Submission Guidelines](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=app%20store%20submission%20guidelines), которые вы, как разработчик, обязаны изучить.

Да даже можно просто погуглить.

**Comment by sevabill** [comment]
Эти ошибки были исправлены в текущем релизе:
https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/2.0.1
А именно, в файл **AviasalesSDKTemplate-Info.plist** были добавлены строки

`<key>NSBluetoothPeripheralUsageDescription</key>`
`<string>Some ad content may access bluetooth</string>`
`<key>NSCalendarsUsageDescription</key>`
`<string>Some ad content may access calendar</string>`
