### ISSUE TITLE
Linker error: library not found for -lAXRatingView

### ISSUE THREAD

**Issue by CRivlaldo** [KosyanMedia/Aviasales-iOS-SDK#35]
When I was trying to build Aviasales-iOS-SDK-2.0.1, I got linking error:
_ld: library not found for -lAXRatingView_

Also it's a lot of warnings like
_ld: warning: directory not found for option '-L/Users/vladimir/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ghzibqhbjfuogcfejcivobnsithe/Build/Products/Debug-iphoneos/AXRatingView'_

or

_ld: warning: directory not found for option '-F/Users/vladimir/Documents/xcode projects/Aviasales-iOS-SDK-2.0.0/AviasalesSDKTemplate/Source/Libs/Appodeal/Adapters/APDAdColonyAdapter.embeddedframework'_

I follow next instructions before building the template:
1. Download sources
2. Execute "pod install"

It's the same error for 2.0.0 version of SDK.

I use Xcode 8, maybe it's the reason.

**Comment by diniska** [comment]
It looks like ```AXRatingView``` was not loaded by cocoapods. Try executing ```pod install``` again. And also check if you use ```xcodeproj``` instead of ```xcworkspace```. Full-screen screenshot could also be helpful to solve this "issue".

**Comment by CRivlaldo** [comment]
> And also check if you use xcodeproj instead of xcworkspace.
Now I get it. Thank you and sorry for the stupid ticket!
