### ISSUE TITLE
want to use this SDK in my project.

### ISSUE THREAD

**Issue by NiteshKhandal** [KosyanMedia/Aviasales-iOS-SDK#37]
hello 

I like this SDK after seeing the screenshots and i want to use it in my project which is in swift 3.0. In my project user can search flights and book also.
so please look into this as soon as possible because it is very urgent for me right now.

kindly replying me fast.

Regard
Nitesh

**Comment by glassoff** [comment]
Hello

In order to use our SDK in your project you have to connect it by [CocoaPods](https://cocoapods.org/pods/AviasalesSDK).

If you want to integrate our interface from Template project, you have to read [these instructions](https://github.com/KosyanMedia/Aviasales-iOS-SDK/blob/master/TemplateIntegration.md)

**Comment by NiteshKhandal** [comment]
no actually i want only use api from your sdk so can you suggest me that how can i call the api's. And one more thing that i download the github but here i face some 3 errors like : 

1. diff: /../Podfile.lock: No such file or directory
2. diff: /Manifest.lock: No such file or directory
3. error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

frankly speaking 

In order to use our SDK in your project you have to connect it by CocoaPods.
in this line i can't understand how to use. here i use 

pod 'AviasalesSDK', '~> 2.0.0'         in my pod file and i am coding in swift 3.0.

so please suggest me and take me out from this error.

**Comment by glassoff** [comment]
Did you install CocoaPods?
Please read documentation about using CocoaPods [https://cocoapods.org](https://cocoapods.org)

**Comment by NiteshKhandal** [comment]
Hello 
Below i attach my project's .zip file. so please check it's pod file and all the process what we need to use your SDK.

Please reply me fast.

Regards
Nitesh

[BookFlightApi.zip](https://github.com/KosyanMedia/Aviasales-iOS-SDK/files/650996/BookFlightApi.zip)

**Comment by glassoff** [comment]
Hello

I checked your project:
- After adding CocoaPods to project you have to open xcworkspace file in xcode
- AviasalesSDK pod should be connected to BookFlightApi target (not BookFlightApiTests) - fix your podfile
- After execution ‘pod install’ you can include our SDK by writing ‘import AviasalesSDK’ in file where you want to use SDK
