### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by generalboost** [KosyanMedia/Aviasales-iOS-SDK#38]
1. Is it possible to change only the color of the header ? If yes, what is the field I should change the colorin the JRColorscheme ? 

2. Do you have existing JRColorscheme files with blue colors you could send me over to copy paste? 

3. How is possible to replace the small round in the main menu with icons ? Where are those small round located in the code ? 

Thanks,

**Comment by sevabill** [comment]
Sorry, we don't provide such thorough support of our template app. This template app is just an example of what can be done using our SDK.
Please consult any 3rd party developer to help you fulfill your requirements.
As an option I can suggest you to wait a few weeks until we release a new version of our template app. It will provide a nicer interface, a number of already prepared color schemes and icons on the search form.
