### ISSUE TITLE
Статистика рейса.

### ISSUE THREAD

**Issue by ADevelopStudio** [KosyanMedia/Aviasales-iOS-SDK#40]
Не смог найти как получить статистику по рейсу как в Aviasales app с временем задержки обычным и т.д.
Это возможно в SDK?

**Comment by diniska** [comment]
К сожалению, SDK сейчас не предоставляет возможность получать статистику рейса. Если она нужна для вашего приложения, то лучше всего воспользоваться каким-нибудь сервисом, предоставляющим такие данные.

**Comment by ADevelopStudio** [comment]
Спасибо!
