### ISSUE TITLE
[!] Unable to find a specification for `AviasalesSDK (~> 2.0.2)`

### ISSUE THREAD

**Issue by theoremreach** [KosyanMedia/Aviasales-iOS-SDK#42]
When trying to do a `pod install` it seems that it can't find the AviasalesSDK. Any idea why not or how we can fix that?

**Comment by geekkon** [comment]
Hello, try to run 'pod repo update' before 'pod install'. Also, you can run 'pod install' in verbose mode using 'pod install --verbose' command to get more info about installation process.
