### ISSUE TITLE
Georgian Lari

### ISSUE THREAD

**Issue by maxuna14** [KosyanMedia/Aviasales-iOS-SDK#45]
Hello, please add on ios app Georgian Lari, becouse we have on WL GEL, also we have on android app, and now we want to produce Ios app, but here no Georgian lari currency, In georgian by legislation is prohibited to display prices in another currencies like USD or EUR, please add GEL, or sent me how to add gel to my app

Thank you

**Comment by maxuna14** [comment]
In previous version i had Georgian lari as default currency

**Comment by sevabill** [comment]
Hi, sorry for the delay, we've added GEL in the latest release: [https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/3.0.2](url)
