### ISSUE TITLE
How to change default currency ?

### ISSUE THREAD

**Issue by AdrienV** [KosyanMedia/Aviasales-iOS-SDK#50]
Hi,
Thanks for this nice work ! 
How to change default currency please ?
Thanks.

**Comment by chebotovanton** [comment]
Hi,
There is an InteractionManager keeping the selected currency. And on init() it creates the currency if there's none selected. So locate init() method in InteractionManager.swift file:

```
override init() {
    super.init()
    if let savedCurrency = self.loadCurrency() {
        currency = savedCurrency
    } else {
        let currencyCode = Locale.current.currencyCode ?? ""
        currency = CurrencyManager.shared.getCurrency(withCode: currencyCode) ??
 CurrencyManager.shared.defaultCurrency()
    }
}
```

and replace 

```
let currencyCode = Locale.current.currencyCode ?? ""
currency = CurrencyManager.shared.getCurrency(withCode: currencyCode) ?? CurrencyManager.shared.defaultCurrency()
```

with any currency created by it's code. For example:

```
currency = CurrencyManager.shared.getCurrency(withCode: "EUR")
```

And here you go! Euro is the default currency now!

List of available currencies can be found in CurrencyStore.swift file.

**Comment by AdrienV** [comment]
Perfect, it works !

Thanks for your quick reply :)
