### ISSUE TITLE
app rejected in itune store

### ISSUE THREAD

**Issue by bapparabi** [KosyanMedia/Aviasales-iOS-SDK#51]
1.0 Binary Rejected
Guideline 2.3.8 - Performance - Accurate Metadata We noticed that the app name to be displayed on the App Store and the app name displayed 

can you tell me what this mean an how to solve it

**Comment by bapparabi** [comment]
Jul 28, 2017 at 4:34 AM
From Apple

    2. 3 Performance: Accurate Metadata
    4. 1 Design: Copycats

Guideline 2.3.8 - Performance - Accurate Metadata


We noticed that the app name to be displayed on the App Store and the app name displayed on the device do not sufficiently match, which makes it difficult for users to find the app they just downloaded. The app names are:

- Name on the App Store: Cheap Flight & Hotels Search Engine

- Name displayed on the device: TAG

To resolve this issue, please change one or both names so they are more similar and the user can easily locate the app they just downloaded. It is important not to change your Bundle Identifier, which is used to uniquely identify your app in the App Store. Changing the Bundle Identifier will prevent users from upgrading and will effectively introduce a new app rather than an update.

Resources

For information on how to revise your device name, please review Technical Q&A QA1823: Updating the Display Name of Your App and Technical Q&A QA1892: Making the app name displayed on a device consistent with the name in iTunes Connect.

For information on changing the app name and other metadata in iTunes Connect, please review the View and edit app information section of iTunes Connect Developer Help.

For resources on selecting a memorable and unique app name, you may want to review the App Store Product Page information available on the Apple developer portal.

Guideline 4.1 - Design - Copycats


Your app or its metadata appears to contain misleading content. Specifically, your app includes content that resembles http://travelaffiliateguru.com/ without the necessary authorization.

Please see attached screenshots for details.

Next Steps

Please demonstrate your relationship with any third-party brand owners represented in your app.

These attachments may display potentially objectionable content, such as nudity, pornography, and profanity.

http://a977.phobos.apple.com/us/r30/Purple128/v4/69/e3/03/69e303e9-f27b-8a70-ba63-e6b8164093ea/attachment-4178086428389619278Screenshot-0727-160310.png?downloadKey3=1501686094_c3c73b65c43c477fb84cf4be7d3c9e08

**Comment by iliakukharev** [comment]
Hi bapparabi,
You got your app rejected because of

**Guideline 2.3.8 - Performance - Accurate Metadata**
You don't have app name in your app title in iTunes Connect.
Please change your app title in iTunes Connect to 
> AppName — Small description
Or copy here your app title from iTunes Connect and app name on iPhone home screen.

**Guideline 4.1 - Design - Copycats**
You have to confirm your relationship with http://travelaffiliateguru.com/ website. Are you an owner?  Attach necessary documents in dialog with a reviewer.

**Comment by bapparabi** [comment]
thanks i will check it aslo they rejected ipad design 

You got your app rejected because of

http://a977.phobos.apple.com/us/r30/Purple128/v4/69/e3/03/69e303e9-f27b-8a70-ba63-e6b8164093ea/attachment-4178086428389619278Screenshot-0727-160310.png?downloadKey3=1501686094_c3c73b65c43c477fb84cf4be7d3c9e08
