### ISSUE TITLE
Tests OK, crash when archive ? (rejected by itunes store)

### ISSUE THREAD

**Issue by AdrienV** [KosyanMedia/Aviasales-iOS-SDK#54]
Hello,

My app is rejected by itunes store, because the app crash on launch. But when I test in xcode (fictive or real devices) in development mode everything work good.

Could you help me to know what is this problem ? 

See logs in attached files.

Thanks for your help.

**Comment by AdrienV** [comment]
[VOL974-2017-08-02-121040.txt](https://github.com/KosyanMedia/Aviasales-iOS-SDK/files/1197303/VOL974-2017-08-02-121040.txt)

**Comment by mkll** [comment]
Are you really developer, dude? I see you can write in English, but should I think you cannot read?

> *** Terminating app due to uncaught exception 'FABException', reason: '[Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.'
terminating with uncaught exception of type NSException

**Comment by geekkon** [comment]
Hello, the problem is you are trying to initialize Fabric but you info.plist is not set properly.
You can remove Fabric initialization in JRAppLauncher, or check the info.plist settings. There mast by key "Fabric" with type "Dictionary" and "APIKye" inside.

**Comment by AdrienV** [comment]
Hey @mkll , don't worry, be happy my friend. I'm french, I'm WEB developer, specialized on PHP frameworks, I don't know anything in C/C++ or other dev feelings. And my english is very bad too... But I'll be very happy to share a beer with you if you want, and we could speak about real problem on this planet...  ;) 
Take care my friend.

@geekkon thanks for your help man, it was fabric who crash the app. I delete initialization in JRAppLauncher and everything work good now. Thanks so much.

**Comment by mkll** [comment]
@AdrienV, I like your answer, it told me you're nice guy. ;) But you really should know at least basics when you getting in touch with iOS dev as well as with any other dev, right? Hmm, it sounds reasonable. ;)
Anyway, you can continue to fill App Store with clones of the same app along with 245636 already existed clones. I believe Apple will be happy with this. ;)

**Comment by AdrienV** [comment]
@mkll thanks for your advice man, but this app is furnished by travelpayout and this sdk is precisely there for those who do not have the knowledge or the possibility to realize a mobile app for their business. For my specific case, we already have a business in the field of travel, and this sdk totally corresponds to our expectations to provide an additional service to our Internet users.

But one more time, thanks for your advice, I don't have any time to learn iOs dev now, maybe in the future. =)
