### ISSUE TITLE
Design: Spam -- Design: Copycats -- and app not approves 

### ISSUE THREAD

**Issue by bapparabi** [KosyanMedia/Aviasales-iOS-SDK#55]
this will not work any more as apple is creating copycat issue and we try to publish the app and they rejecte 3 times

Design: Copycats
Design: Spam

Your app duplicates the content and functionality of apps submitted to the App Store, which is considered a form of spam.

Apps that simply duplicate content or functionality create clutter, diminish the overall experience for the end user, and reduce the ability of developers to market their apps.

and many rson as we cant use the same sdk and design as they disable the app and not publish it ..

do you have the solution ....??

alos recently google also suspended out app using your andriod sdk

reason

Read through the Webviews and Affiliate Spam article for more details and examples of policy violations.
Make sure your app is compliant with the Spam policy and all other policies listed in the Developer Program Policies. Remember that additional enforcement could occur if there are further policy issues with your apps.
So now no use of your sdks i thing ..

**Comment by wi1son** [comment]
is this still happening?
