### ISSUE TITLE
Please update to newest Swift Version 

### ISSUE THREAD

**Issue by nedbaynepowell** [KosyanMedia/Aviasales-iOS-SDK#58]
I'm having problems with this, I've downloaded it but it's couldn't update to Swift Version 3.2 so on stackoverflow I asked the question and they said to do this: 

Go to https://github.com/KosyanMedia/Hotellook-iOS-SDK-Core, in your podfile update this lines

use_frameworks!
pod 'HotellookSDK', :git => 'https://github.com/KosyanMedia/Hotellook-iOS-SDK-Core.git'
pod 'SwiftProtobuf', :git => 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.902'
And update pod via "pod update" command in console.

Use Swift language version 3.2

After I updated the podfile unfortunately it still doesn't work. Although it's updated to Swift 3.2 there are still problems. Please see my debug on  https://stackoverflow.com/questions/46368595/aviasalessdktemplate-cannot-be-imported-with-swift-3-2

Thanks so much and hope to hear from you soon. 

Best, 
Ned

**Comment by MontakOleg** [comment]
Hi @nedbaynepowell!

In your Podfile try this versions:
```
pod 'HotellookSDK', :git => 'https://github.com/KosyanMedia/Hotellook-iOS-SDK-Core.git', :tag => 'v1.0.2'
pod 'SwiftProtobuf', :git => 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.905'
```

Then `pod update`. 
Let me know if this helped.

**Comment by nedbaynepowell** [comment]
Thanks so much, it works now. :)
