### ISSUE TITLE
xcode update problems.

### ISSUE THREAD

**Issue by petesavva** [KosyanMedia/Aviasales-iOS-SDK#60]
![image](https://user-images.githubusercontent.com/4371442/30791576-48def428-a168-11e7-95b2-ffb56a6bf730.png)

so i updated xcode today..... also updated podfile in the project directory. then updated to swift 4 and all recommended settings. have 6 warnings in swift protobuf....

**Comment by MontakOleg** [comment]
Hello @petesavva

See https://github.com/KosyanMedia/Aviasales-iOS-SDK/issues/58

**Comment by geekkon** [comment]
You also can download updated pod file and reinstall pods
