### ISSUE TITLE
new xcode update crashes HotellookSDK

### ISSUE THREAD

**Issue by petesavva** [KosyanMedia/Aviasales-iOS-SDK#67]
Hi guys,
I started up xcode last night and it did some component update. After that I get the following message:
module compiled with Swift 4.0 cannot be imported in Swift 3.2.2: /Pods/HotellookSDK/Library/HotellookSDK.framework/Modules/HotellookSDK.swiftmodule/x86_64.swiftmodule

is hotellooksdk updated so i can pod update? thanks.

**Comment by petesavva** [comment]
i did a pod update to 1.0.3 still no luck. strange.

**Comment by petesavva** [comment]
temporary solution:
install external Swift 4.0 Toolchain and select it within Xcode -> Preferences -> Components -> Toolchains so you are back with Xcode 9.0 swift toolchain

**Comment by petesavva** [comment]
scratch that. no luck. it starts but crashes with:
 Reason: Incompatible library version: HotellookSDK requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0

**Comment by MontakOleg** [comment]
Hi @petesavva,

check new version of HotellookSDK 1.0.4 + swift-protobuf 1.0.1:

```
pod 'HotellookSDK', '~> 1.0.4'
pod 'SwiftProtobuf', '~> 1.0.1'
```

**Comment by petesavva** [comment]
awesome! thanks guys!
