### ISSUE TITLE
The server is unreachable

### ISSUE THREAD

**Issue by dem7799** [KosyanMedia/Aviasales-iOS-SDK#7]
Run iOS 9 on xcode 7.1 and see this error: "The server is unreachable" when start search (check 3 days)

**Comment by sevabill** [comment]
Please checkout [new SDK](https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases) and [new integration steps](https://github.com/KosyanMedia/Aviasales-iOS-SDK/blob/master/README_EN.md)
