### ISSUE TITLE
Module compiled with Swift 4.0.2 cannot be imported in Swift 3.2:

### ISSUE THREAD

**Issue by qpbp** [KosyanMedia/Aviasales-iOS-SDK#70]
Got an error.

Steps:
1. Download [this](https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/3.0.4) version of SDK.
2. Unzip, rename SDK folder to required name.
3. Open terminal, go to the SDK folder, run `pod install --repo-update`
4. Open `AviasalesSDKTemplate.xcworkspace` in SDK folder, using Xcode (Xcode 9.0.1, Build version 9A1004)
5. Open [<SDK folder>/AviasalesSDKTemplate/Source/Config.h](url) file 
6. Add appropriate data to  the`kJRPartnerMarker` and `kJRAPIToken` fields
7. Select Device - Iphone 7
8. Product -> Run

**Actual Result:** 
`<unknown>:0: error: module compiled with Swift 4.0.2 cannot be imported in Swift 3.2: /Users/roman/Projects/testProject/Pods/HotellookSDK/Library/HotellookSDK.framework/Modules/HotellookSDK.swiftmodule/x86_64.swiftmodule`

<img width="869" alt="screen shot 2017-12-04 at 10 39 25 pm" src="https://user-images.githubusercontent.com/7635002/33575042-0fd4b82a-d944-11e7-8f21-f8637a85f950.png">

**Expected Result:** 
See emulator with working app.

**Comment by zykis** [comment]
Same here

**Comment by zykis** [comment]
Same here

**Comment by qpbp** [comment]
Also, I checked the [previous release of SDK ](https://github.com/KosyanMedia/Aviasales-iOS-SDK/releases/tag/3.0.3)and `Product -> Run` works well in the same version of Xcode (Xcode 9.0.1, Build version 9A1004).

**Comment by qpbp** [comment]
Duplicate #67  ???

**Comment by zykis** [comment]
#67 is crash. This is compile-time error, so doubt it's a duplicate

**Comment by geekkon** [comment]
Hello, you should use Xcode 9.1 for last SKD Template.
