### ISSUE TITLE
Airline logo and flight number

### ISSUE THREAD

**Issue by petesavva** [KosyanMedia/Aviasales-iOS-SDK#75]
Some airline logos don’t appear and the flight number associated shows as xx-1. Is there a way to fix or eliminate those results?

Also is there a way to show the flight Number in the initial results so the user doesn’t have to tap the specific result first?

Thank you and happy new year!

**Comment by geekkon** [comment]
Yes, some airlines does not shows that data, but you can filter them to avoid displaying in search results. 

Flight number is a flight property, in one flight segment there can be more than one flight. But you can add additional label in sera result ticket and display all flights in segment :)

**Comment by petesavva** [comment]
Is it possible to contract you for some of these mods? thanks.

**Comment by geekkon** [comment]
In JRSearchResultsVC.m there is a filter initialization 
````
- (JRFilter *)filter {
    if (!_filter) {
        _filter = [[JRFilter alloc] initWithTickets:self.response.tickets searchInfo:self.searchInfo];
        _filter.delegate = self;
    }
    return  _filter;
}
````
You can apply filter to `self.response.tickets` which should iterate throw all tickets -> flight segments -> flights and check if `number` contains "xx"

**Comment by geekkon** [comment]
And flight number can be build the same way. You already show flight segment string in ticket cell. Iterate throw flights in segment and concat string with numbers :)

**Comment by petesavva** [comment]
thank you!
