### ISSUE TITLE
Missing Integration wiki 

### ISSUE THREAD

**Issue by sashahilton00** [KosyanMedia/Aviasales-iOS-SDK#80]
Hi,

Thanks for this SDK, makes integration of Travelpayouts service much simpler than having to write an interface for it in our apps. What I have noticed though is that since v3.0 was released, the integration document and all cocoapods info was removed from the repo. Are there any plans to add an updated integration document for integrating this into our Swift projects and such? It would be immensely helpful. Thanks.

**Comment by geekkon** [comment]
Hello! Since we released 3.0 and added Hotels tab, simple integration manual is no longer actual, because we use UITabBarController as a root, and it became a little tricky to describe simple integration.

**Comment by sashahilton00** [comment]
Good to know, is there any plan to make it easier to integrate?

**Comment by geekkon** [comment]
It is can't be done easy, so the answer is no. TabBarController has to be a root view controller, so it's not an option to integrate in a existing app, which has a side menu for example, or another tab bar controller.

**Comment by sashahilton00** [comment]
Ok, thanks for the info.
