### ISSUE TITLE
Over 700 warnings

### ISSUE THREAD

**Issue by karo2204** [KosyanMedia/Aviasales-iOS-SDK#82]
Is this normal? I just imported everything into Xcode and compiled it into an app and Xcode 9.3 shows over 700 warnings. Also it is not in Swift 4. 

Will this be fixed anytime soon?

**Comment by geekkon** [comment]
Hello, we have just released version 3.2, that supports Swift 4. A lot of warnings resolved

**Comment by karo2204** [comment]
Thanks a lot. Will try it immediately.
