### ISSUE TITLE
installing pod issues

### ISSUE THREAD

**Issue by Romil12345** [KosyanMedia/Aviasales-iOS-SDK#84]
appodeal not installing in my temple when repo update give me solution please..

**Comment by geekkon** [comment]
Hello! Sometimes appodeal fails to install. Try later until success. It is usually helps ))

**Comment by Romil12345** [comment]
i tryed but always fails (:

**Comment by geekkon** [comment]
Try verbose mode, when pod install / update. Maybe logs will show something useful

**Comment by gerchicov-bp** [comment]
I have the same issue. In general Appodeal is sdk for ads. Why does it belong to this repo and can't be disabled?

**Comment by geekkon** [comment]
Because it is an SDK Template repo. And it provides ads support. You can remove appodeal pod in podfile and change the according code in sample. Or you can use SDK Core and build your own UI :)

**Comment by geekkon** [comment]
@gerchicov-bp this repo is what you need 
https://github.com/KosyanMedia/Aviasales-iOS-SDK-Core
