### ISSUE TITLE
Code is not working 

### ISSUE THREAD

**Issue by MandeepSingh1** [KosyanMedia/Aviasales-iOS-SDK#85]
Hello Team, I have downloaded the SDK, and am running the code, But when all the code is compile. Am facing this issue:- 

/Users/osvinuser/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-glocdbicayqzeleiwweeydojbctq/Build/Intermediates.noindex/AviasalesSDKTemplate.build/Debug-iphonesimulator/AviasalesSDKTemplate.build/Script-9FC7BD251EDC76590034D7DB.sh: line 2: /Users/osvinuser/Documents/Mandeep: No such file or directory

![screen shot 2018-06-26 at 2 36 51 pm](https://user-images.githubusercontent.com/11526089/41901510-b74c4172-794e-11e8-9d0f-bde4fa63b02f.png)

Also, Am using the Xcode 9.4, for compiling the code. But Am not able to run the code. If you guys can help me whats going wrong with my code and if I miss something just lemme know. 

How can I resolve this issue. 

Cheers

**Comment by Romil12345** [comment]
in hotel tab book now button click and open web view but in web view show details button not work plz give me proper solution..

**Comment by geekkon** [comment]
What do you mean "show details button". Is it a part of a web view content?

**Comment by Romil12345** [comment]
yeah! in web view..

**Comment by geekkon** [comment]
It is probably a specific web content issue. I can not help here.

**Comment by Romil12345** [comment]
in coding apply any restriction ??

**Comment by geekkon** [comment]
There are some agencies, which tries to open a new window for a web view. What search do you perform? What agency choose?

**Comment by Romil12345** [comment]
show details button.

**Comment by Romil12345** [comment]
i uses Aviasale SDK code for..

**Comment by geekkon** [comment]
I am asking you for search params. Then agency to pick.
Which device do you use?
