### ISSUE TITLE
Binary Rejected

### ISSUE THREAD

**Issue by faisalface** [KosyanMedia/Aviasales-iOS-SDK#86]
hello
my app Binary Rejected from apple store

Guideline 2.3.1 - Performance

Your app includes a version of an SDK from Yandex that violates the App Store Review Guidelines. The version of the Yandex SDK you are using in your app attempts to hide the use of private APIs. This is a violation of Sections 2.3.1 and 2.5.1 of the App Store Review Guidelines.

Guideline 2.3.1: Don’t include any hidden or undocumented features in your app.

Guideline 2.5.1: Apps may only use public APIs.

Next Steps

To resolve this issue, please either remove the Yandex SDK entirely from your app, or revise your app to utilize version 2.9.8 or 3.1.2 of the Yandex SDK. Once you have made one of those changes, resubmit your binary for review.

Guideline 2.3.3 - Performance - Accurate Metadata

**Comment by geekkon** [comment]
Hello, our template does not include Yandex SDK, and don't use any private API.

**Comment by anton-plebanovich** [comment]
Hi @geekkon , got the same issue, it's because you are using outdated Appodeal framework, this is message from Appodeal:

> Recently you may have received notifications from the App Store about issues connected to Yandex SDK and the violation of the App Store Review Guidelines. 
> To resolve this matter, please make sure to update Appodeal SDK to the version 2.4.4. 
> SDK 2.4.4 includes the updated Yandex SDK adapter, so everything should work smoothly once you upgrade your Appodeal SDK. 

Could you possibly update your template to use the latest Appodeal SDK?

**Comment by geekkon** [comment]
Hello, we already know the problem and work on it. There will be release soon (we've reintegrated appodeal framework).
