### ISSUE TITLE
how to remove the ads?

### ISSUE THREAD

**Issue by hensonmel** [KosyanMedia/Aviasales-iOS-SDK#88]
i do not want to use the appodeal ads feature and i do not have the appodeal key. is there a way to completely remove appodeal sdk?

**Comment by geekkon** [comment]
Hello! We've just published new release. Check it out. If you leave appodeal key in config empty - there will not be any ads. Is it help?

**Comment by hensonmel** [comment]
yes, it is working now without ads.
