### ISSUE TITLE
XCode 10 and Swift 4.2

### ISSUE THREAD

**Issue by Nalorokk** [KosyanMedia/Aviasales-iOS-SDK#90]
Old version of Swift in this project prevents build with latest Xcode

**Comment by geekkon** [comment]
Hello. We are currently fixing the problem

**Comment by gibbor178** [comment]
Could you please provide an update as to when this fix will be in place?
Thanks

**Comment by geekkon** [comment]
Hello! Check out new release 3.5. It fixes these issues.
