### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MISIEK22** [KosyanMedia/Aviasales-iOS-SDK#93]
Following the instructions, have cocoapods installed and I cannot build.

:-1: Multiple commands produce '/Users/misiek/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ddyypcthepxrdahciiahjsvyjogv/Build/Products/Debug-iphoneos/AviasalesSDK/AviasalesSDKResources.bundle/Info.plist':
1) Target 'AviasalesSDK-AviasalesSDKResources' (project 'Pods') has copy command from '/Users/misiek/Desktop/travelo/Pods/AviasalesSDK/Library/Resources/Info.plist' to '/Users/misiek/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ddyypcthepxrdahciiahjsvyjogv/Build/Products/Debug-iphoneos/AviasalesSDK/AviasalesSDKResources.bundle/Info.plist'
2) Target 'AviasalesSDK-AviasalesSDKResources' (project 'Pods') has process command with output '/Users/misiek/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ddyypcthepxrdahciiahjsvyjogv/Build/Products/Debug-iphoneos/AviasalesSDK/AviasalesSDKResources.bundle/Info.plist'

**Comment by geekkon** [comment]
Hello! You can fix it by changing AviaslaesSDK version in Podfile to 3.1.3. Or you can wait until new release will be submitted.

**Comment by MISIEK22** [comment]
Hi geekkon. thanks for the reply! I've made the change to the file but it hasn't changed the error. I also get a new few errors now.

<unknown>:0: error: module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/misiek/Desktop/travelo/Pods/HotellookSDK/Library/HotellookSDK.framework/Modules/HotellookSDK.swiftmodule/arm64.swiftmodule

**Comment by MISIEK22** [comment]
thanks for the help. that disappeared by I keep getting this error again and swift errors :(


Showing Recent Messages
:-1: Multiple commands produce '/Users/misiek/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ddyypcthepxrdahciiahjsvyjogv/Build/Products/Debug-iphonesimulator/AviasalesSDK/AviasalesSDKResources.bundle/Info.plist':
1) Target 'AviasalesSDK-AviasalesSDKResources' (project 'Pods') has copy command from '/Users/misiek/Desktop/travelo/Pods/AviasalesSDK/Library/Resources/Info.plist' to '/Users/misiek/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ddyypcthepxrdahciiahjsvyjogv/Build/Products/Debug-iphonesimulator/AviasalesSDK/AviasalesSDKResources.bundle/Info.plist'
2) Target 'AviasalesSDK-AviasalesSDKResources' (project 'Pods') has process command with output '/Users/misiek/Library/Developer/Xcode/DerivedData/AviasalesSDKTemplate-ddyypcthepxrdahciiahjsvyjogv/Build/Products/Debug-iphonesimulator/AviasalesSDK/AviasalesSDKResources.bundle/Info.plist'

**Comment by geekkon** [comment]
It has to be fixed by AviaslaesSDK 3.1.3  update. Try clean project / derived data

**Comment by geekkon** [comment]
Hello! Check out new release 3.5. It fixes these issues.
